### ISSUE TITLE
Preparing the Native Ligand

### ISSUE THREAD

**Issue by su-spec** [quantaosun/labodock_binder#1]
My pdb doesn't have native ligand, so why doesn't it run as an optional Preparing the Native Ligand, or why does running this notebook without Native Ligand cause an error

**Comment by quantaosun** [comment]
Hi there, you are supposed to have a general idea where you molecule bind to the target protein regardless there is native ligand or not. The only reason native ligand matters is to generate a docking grid, and a native ligand is the most common way to define the location of the grid. If there is no native ligand, you have to use other methods to generate the grid. You can try to skip " Prepare native ligand" section. When runnig "05 | Setting Up Grid Box" section, please select methods that do not depend on native ligand.

**Comment by quantaosun** [comment]
Following the previous issue, here is a more specific example of using a structure without a native ligand. For example;e now we need to deal with PDB 1AKI without any native ligand, we are interested in how a benzene molecule (c1ccccc1) bind to an estimated area of reside 58 and 59 of 1AKI. What need to be done, is to lead the native ligand variable native_lig blank, and run all the native ligand related cells as if there were native ligand despite there are errors. When reaching the docking grid cell, we just need to select the grid generation method to "Defined-by-Res" and put 58,59 as the residue number variable. Run all the rest as normal, that will do the job.
